## roles/freeipa/tasks/kra.yml
## in KRA: templates, restart httpd, command "pkispawn -s {{KRA template path}} -f /path/to/kra.cfg
##         restart pki-tomcatd@pki-tomcat.service and go on with:
## https://www.freeipa.org/page/Howto/IPAv3_Add_a_KRA
---
- name: Install KRA packages
  dnf:
    name: '{{ item }}'
    state: latest
  with_items:
    - bind
    - bind-dyndb-ldap
    - pki-kra

- name: Temporary KRA file
  template:
    src: KRA.j2
    dest: /tmp/KRA

- name: Update IPA Proxy Configuration
  template:
    src: ipa-pki-proxy.conf
    dest: /etc/httpd/conf.d/ipa-pki-proxy.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - 'restart httpd'

- name: Add the KRA
  command: pkispawn -s /tmp/KRA -f {{ kraconf_path }}
  notify:
    - 'restart pkitomcat'

- name: Remove Temp KRA
  file:
    path: /tmp/KRA
    state: absent
...
