# roles/ansible-role-freeipa/vars/default.yml
# vim:ft=yaml.ansible:
ipaserver_packages: [ "ipa-server", "python3-libselinux" ]
ipaserver_packages_dns: [ "ipa-server-dns" ]
ipaserver_packages_adtrust: [ "freeipa-server-trust-ad" ]
